### ISSUE TITLE
执行bash make-7b-cn.sh时报错

### ISSUE THREAD

**Issue by syusama** [soulteary/docker-llama2-chat#12]
$ bash make-7b-cn.sh
ERROR: could not find docker: CreateFile docker: The system cannot find the file specified.
2023/08/01 17:02:02 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
ERROR: could not find docker: CreateFile docker: The system cannot find the file specified.
![屏幕截图 2023-08-01 171446](https://github.com/soulteary/docker-llama2-chat/assets/16223129/bdcbe131-211a-4f13-b959-c6a9d02c53db)

**Comment by syusama** [comment]
退回上级目录执行bash scripts/make-7b-cn.sh就好了

**Comment by soulteary** [comment]
https://github.com/soulteary/docker-llama2-chat/issues/14
