### ISSUE TITLE
执行bash scripts/make-7b-cn.sh，最终报错ERROR: failed to solve: soulteary/llama2:base: docker.io/soulteary/llama2:base: not found

### ISSUE THREAD

**Issue by syusama** [soulteary/docker-llama2-chat#13]
执行bash scripts/make-7b-cn.sh
跑了大概半个小时，最终报错ERROR: failed to solve: soulteary/llama2:base: docker.io/soulteary/llama2:base: not found
![屏幕截图 2023-08-01 180355](https://github.com/soulteary/docker-llama2-chat/assets/16223129/c0126a03-8011-4070-82a1-2c3f00055cd8)

**Comment by soulteary** [comment]
https://github.com/soulteary/docker-llama2-chat/issues/14

**Comment by shaojiankui** [comment]
docker pull nvcr.io/nvidia/pytorch:23.06-py3
