### ISSUE TITLE
soulteary/llama2:base not found

### ISSUE THREAD

**Issue by songbotao** [soulteary/docker-llama2-chat#8]
你好，我在通过bash运行脚本的时候发生了如下错误，我也去了dockerhub上的soulteary上查看了镜像，好像没有tag为base的镜像，请问这个错误是为什么呢

Step 1/3 : FROM soulteary/llama2:base
manifest for soulteary/llama2:base not found: manifest unknown: manifest unknown

**Comment by soulteary** [comment]
你好，在之前的教程里，因为nvidia官方镜像比较大，所以自己构建会快很多，故没有上传 DockerHub。

**Comment by xiaoweiwang74** [comment]
怎么解决呢？我也遇到这个问题

**Comment by soulteary** [comment]
跟着教程走一遍，镜像就有啦。 @xiaoweiwang74

**Comment by soulteary** [comment]
https://github.com/soulteary/docker-llama2-chat/issues/14
